### PR TITLE
#55 adding support for gradle

### PR DESCRIPTION
**Pull request by sunydepalpur**
https://github.com/TheNewEconomy/EconomyCore/issues/55

### CODE REVIEW

**Comment by sunydepalpur** [comment]
Screenshot 2023-09-04 at 6 23 55 PM

**Comment by creatorfromhell** [comment]
Cheers, I'll review this tomorrow.

**Comment by creatorfromhell** [comment]
> Screenshot 2023-09-04 at 6 23 55 PM

Downloading and running a gradle build locally produces this result:

image

**Comment by sunydepalpur** [comment]
> > Screenshot 2023-09-04 at 6 23 55 PM
> 
> Downloading and running a gradle build locally produces this result:
> 
> image

You can use intellIJ for the build, I can share the, build approach

**Comment by sunydepalpur** [comment]
> > > Screenshot 2023-09-04 at 6 23 55 PM
> > 
> > 
> > Downloading and running a gradle build locally produces this result:
> > image
> 
> You can use intellIJ for the build, I can share the, build approach

Added the build configs in PR

**Comment by creatorfromhell** [comment]
> > > > Screenshot 2023-09-04 at 6 23 55 PM
> > > 
> > > 
> > > Downloading and running a gradle build locally produces this result:
> > > image
> > 
> > 
> > You can use intellIJ for the build, I can share the, build approach
> 
> Added the build configs in PR

If I remember correctly, this is something in the buildSrc folder, not the intellij configs.

**Comment by creatorfromhell** [comment]
Reviewing this in more detail. This PR is severely flawed. Firstly, non of the dependencies have any repositories ported over to the gradle files, secondly the java conventions plugin isn't really needed in this case, it should be the "java-library" one. In essence, this looks like someone just ran gradle init, pushed it into a branch and slapped a PR for it.

**Review by creatorfromhell — CHANGES_REQUESTED** [review]
Repositories for dependencies need to be actually included, gradle logic needs fixed beyond just typing "gradle init". Intellij config files may be removed as these weren't the issue.

**Comment by creatorfromhell** [comment]
PR is severely flawed, closing.

**Pull request closed without merging**
